medical_words = {
    "acute", "chronic", "diagnosis", "prognosis", "symptom", "syndrome",
    "therapy", "treatment", "medication", "prescription", "allergy",
    "inflammation", "infection", "benign", "malignant", "biopsy",
    "carcinoma", "sarcoma", "edema", "fracture", "hypertension",
    "hypotension", "diabetes", "arthritis", "asthma", "bronchitis",
    "cardiac", "cerebral", "dermatitis", "gastritis", "hepatitis",
    "nephritis", "neuropathy", "osteoporosis", "pneumonia", "tachycardia",
    "bradycardia", "anemia", "ischemia", "embolism", "thrombosis",
    "pathology", "etiology", "epidemiology", "radiology", "oncology",
    "pediatrics", "geriatrics", "gynecology", "urology", "dermatology",
    "cardiology", "neurology", "endocrinology", "gastroenterology",
    "hematology", "immunology", "pulmonology", "rheumatology", "surgery",
    "vaccine", "antibiotic", "antiviral", "antifungal", "analgesic",
    "antipyretic", "anti-inflammatory", "sedative", "anesthetic", "diuretic",
    "laxative", "antacid", "antihistamine", "antidepressant", "anticoagulant",
    "cholesterol", "glucose", "insulin", "hormone", "enzyme", "antibody",
    "antigen", "bacteria", "virus", "fungus", "parasite", "cell", "tissue",
    "organ", "system", "anatomy", "physiology", "pathophysiology",
    "homeostasis", "metabolism", "catabolism", "anabolism", "respiration",
    "circulation", "digestion", "excretion", "reproduction", "nervous system",
    "endocrine system", "immune system", "lymphatic system", "skeletal system",
    "muscular system", "integumentary system", "urinary system",
    "respiratory system", "cardiovascular system", "digestive system",
    "reproductive system", "central nervous system", "peripheral nervous system"
}
